### ISSUE TITLE
Rename number to '`num` in data attribute of expression

### ISSUE THREAD

**Issue by karthik-suresh** [influenzanet/survey-engine.dart#2]
`number` is used instead of `num`  as `num` is a keyword in Dart.

**Comment by phev8** [comment]
what is the issue here? the json will be received with 'num' that has to be mapped to whatever attribute name you implement in the dart model.

**Comment by karthik-suresh** [comment]
Nothing specific I just added as a reminder to edit it. Will remove the issue.
